# Generated by Django 4.1.4 on 2022-12-29 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prediccion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prediccion',
            name='Arritmia',
            field=models.IntegerField(choices=[(0, 'NO'), (1, 'SI')], default=0),
        ),
        migrations.AlterField(
            model_name='prediccion',
            name='FEVI',
            field=models.IntegerField(choices=[(0, 'NO'), (1, 'SI')], default=0),
        ),
        migrations.AlterField(
            model_name='prediccion',
            name='FIB_AURIC',
            field=models.IntegerField(choices=[(0, 'NO'), (1, 'SI')], default=0),
        ),
        migrations.AlterField(
            model_name='prediccion',
            name='ICC',
            field=models.IntegerField(choices=[(0, 'NO'), (1, 'SI')], default=0),
        ),
        migrations.AlterField(
            model_name='prediccion',
            name='Isquemia',
            field=models.IntegerField(choices=[(0, 'NO'), (1, 'SI')], default=0),
        ),
        migrations.AlterField(
            model_name='prediccion',
            name='SHOCK',
            field=models.IntegerField(choices=[(0, 'NO'), (1, 'SI')], default=0),
        ),
        migrations.AlterField(
            model_name='prediccion',
            name='TV_FV_PCR',
            field=models.IntegerField(choices=[(0, 'NO'), (1, 'SI')], default=0),
        ),
        migrations.AlterField(
            model_name='prediccion',
            name='ada',
            field=models.IntegerField(choices=[(0, 'NO'), (1, 'SI')], default=0),
        ),
        migrations.AlterField(
            model_name='prediccion',
            name='aminas',
            field=models.IntegerField(choices=[(0, 'NO'), (1, 'SI')], default=0),
        ),
        migrations.AlterField(
            model_name='prediccion',
            name='anemia',
            field=models.IntegerField(choices=[(0, 'NO'), (1, 'SI')], default=0),
        ),
        migrations.AlterField(
            model_name='prediccion',
            name='angina24h',
            field=models.IntegerField(choices=[(0, 'NO'), (1, 'SI')], default=0),
        ),
        migrations.AlterField(
            model_name='prediccion',
            name='anticalcicos',
            field=models.IntegerField(choices=[(0, 'NO'), (1, 'SI')], default=0),
        ),
        migrations.AlterField(
            model_name='prediccion',
            name='anticoagulantes',
            field=models.IntegerField(choices=[(0, 'NO'), (1, 'SI')], default=0),
        ),
        migrations.AlterField(
            model_name='prediccion',
            name='atencion_inicial',
            field=models.IntegerField(choices=[(0, 'NO'), (1, 'SI')], default=0),
        ),
        migrations.AlterField(
            model_name='prediccion',
            name='avc',
            field=models.IntegerField(choices=[(0, 'NO'), (1, 'SI')], default=0),
        ),
        migrations.AlterField(
            model_name='prediccion',
            name='balon',
            field=models.IntegerField(choices=[(0, 'NO'), (1, 'SI')], default=0),
        ),
        migrations.AlterField(
            model_name='prediccion',
            name='cabg',
            field=models.IntegerField(choices=[(0, 'NO'), (1, 'SI')], default=0),
        ),
        migrations.AlterField(
            model_name='prediccion',
            name='clopidogrel',
            field=models.IntegerField(choices=[(0, 'NO'), (1, 'SI')], default=0),
        ),
        migrations.AlterField(
            model_name='prediccion',
            name='color_piel',
            field=models.IntegerField(choices=[(1, 'Blanca'), (0, 'Otra')], default=1),
        ),
        migrations.AlterField(
            model_name='prediccion',
            name='coronariografia',
            field=models.IntegerField(choices=[(0, 'NO'), (1, 'SI')], default=0),
        ),
        migrations.AlterField(
            model_name='prediccion',
            name='depresion_st',
            field=models.IntegerField(choices=[(0, 'NO'), (1, 'SI')], default=0),
        ),
        migrations.AlterField(
            model_name='prediccion',
            name='diabetes_mellitus',
            field=models.IntegerField(choices=[(0, 'NO'), (1, 'SI')], default=0),
        ),
        migrations.AlterField(
            model_name='prediccion',
            name='dialisis',
            field=models.IntegerField(choices=[(0, 'NO'), (1, 'SI')], default=0),
        ),
        migrations.AlterField(
            model_name='prediccion',
            name='ecg_previo',
            field=models.IntegerField(choices=[(0, 'NO'), (1, 'SI')], default=0),
        ),
        migrations.AlterField(
            model_name='prediccion',
            name='enfermedad_arterias_coronarias',
            field=models.IntegerField(choices=[(0, 'NO'), (1, 'SI')], default=0),
        ),
        migrations.AlterField(
            model_name='prediccion',
            name='enfermedad_cerebro_vascular',
            field=models.IntegerField(choices=[(0, 'NO'), (1, 'SI')], default=0),
        ),
        migrations.AlterField(
            model_name='prediccion',
            name='enfermedad_venosa_periferica',
            field=models.IntegerField(choices=[(0, 'NO'), (1, 'SI')], default=0),
        ),
        migrations.AlterField(
            model_name='prediccion',
            name='epoc',
            field=models.IntegerField(choices=[(0, 'NO'), (1, 'SI')], default=0),
        ),
        migrations.AlterField(
            model_name='prediccion',
            name='estado_vital',
            field=models.IntegerField(choices=[(0, 'Fallecido'), (1, 'Vivo')], default=0),
        ),
        migrations.AlterField(
            model_name='prediccion',
            name='estatinas',
            field=models.IntegerField(choices=[(0, 'NO'), (1, 'SI')], default=0),
        ),
        migrations.AlterField(
            model_name='prediccion',
            name='estreptoquinasa_recombinante',
            field=models.IntegerField(choices=[(0, 'NO'), (1, 'SI')], default=0),
        ),
        migrations.AlterField(
            model_name='prediccion',
            name='fibrilacion_auricular',
            field=models.IntegerField(choices=[(0, 'NO'), (1, 'SI')], default=0),
        ),
        migrations.AlterField(
            model_name='prediccion',
            name='furosemida',
            field=models.IntegerField(choices=[(0, 'NO'), (1, 'SI')], default=0),
        ),
        migrations.AlterField(
            model_name='prediccion',
            name='heparina',
            field=models.IntegerField(choices=[(0, 'NO'), (1, 'SI')], default=0),
        ),
        migrations.AlterField(
            model_name='prediccion',
            name='hiperlipoproteinemia',
            field=models.IntegerField(choices=[(0, 'NO'), (1, 'SI')], default=0),
        ),
        migrations.AlterField(
            model_name='prediccion',
            name='hipertension_arterial',
            field=models.IntegerField(choices=[(0, 'NO'), (1, 'SI')], default=0),
        ),
        migrations.AlterField(
            model_name='prediccion',
            name='horario_llegada',
            field=models.IntegerField(choices=[(0, 'NO'), (1, 'SI')], default=0),
        ),
        migrations.AlterField(
            model_name='prediccion',
            name='ieca',
            field=models.IntegerField(choices=[(0, 'NO'), (1, 'SI')], default=0),
        ),
        migrations.AlterField(
            model_name='prediccion',
            name='indice_killip',
            field=models.IntegerField(choices=[(0, 'NO'), (1, 'SI')], default=0),
        ),
        migrations.AlterField(
            model_name='prediccion',
            name='indice_mkillip',
            field=models.IntegerField(choices=[(0, 'NO'), (1, 'SI')], default=0),
        ),
        migrations.AlterField(
            model_name='prediccion',
            name='infarto_miocardio_agudo',
            field=models.IntegerField(choices=[(0, 'NO'), (1, 'SI')], default=0),
        ),
        migrations.AlterField(
            model_name='prediccion',
            name='insuficiencia_cardiaca_congestiva',
            field=models.IntegerField(choices=[(0, 'NO'), (1, 'SI')], default=0),
        ),
        migrations.AlterField(
            model_name='prediccion',
            name='insuficiencia_renal_cronica',
            field=models.IntegerField(choices=[(0, 'NO'), (1, 'SI')], default=0),
        ),
        migrations.AlterField(
            model_name='prediccion',
            name='intervencion_coronaria_percutanea',
            field=models.IntegerField(choices=[(0, 'NO'), (1, 'SI')], default=0),
        ),
        migrations.AlterField(
            model_name='prediccion',
            name='lugar_trombolisis',
            field=models.IntegerField(choices=[(0, 'NO'), (1, 'SI')], default=0),
        ),
        migrations.AlterField(
            model_name='prediccion',
            name='mpp',
            field=models.IntegerField(choices=[(0, 'NO'), (1, 'SI')], default=0),
        ),
        migrations.AlterField(
            model_name='prediccion',
            name='mpt',
            field=models.IntegerField(choices=[(0, 'NO'), (1, 'SI')], default=0),
        ),
        migrations.AlterField(
            model_name='prediccion',
            name='nitratos',
            field=models.IntegerField(choices=[(0, 'NO'), (1, 'SI')], default=0),
        ),
        migrations.AlterField(
            model_name='prediccion',
            name='otros_diureticos',
            field=models.IntegerField(choices=[(0, 'NO'), (1, 'SI')], default=0),
        ),
        migrations.AlterField(
            model_name='prediccion',
            name='prediccion',
            field=models.IntegerField(choices=[(0, 'Fallecido'), (1, 'Vivo')], default=0),
        ),
        migrations.AlterField(
            model_name='prediccion',
            name='reperfusion',
            field=models.IntegerField(choices=[(0, 'NO'), (1, 'SI')], default=0),
        ),
        migrations.AlterField(
            model_name='prediccion',
            name='scacest',
            field=models.IntegerField(choices=[(0, 'NO'), (1, 'SI')], default=0),
        ),
        migrations.AlterField(
            model_name='prediccion',
            name='sexo',
            field=models.IntegerField(choices=[(0, 'Femenino'), (1, 'Masculino')], default=0),
        ),
        migrations.AlterField(
            model_name='prediccion',
            name='tabaquismo',
            field=models.IntegerField(choices=[(0, 'NO'), (1, 'SI')], default=0),
        ),
        migrations.AlterField(
            model_name='prediccion',
            name='vam',
            field=models.IntegerField(choices=[(0, 'NO'), (1, 'SI')], default=0),
        ),
    ]
