# Generated by Django 4.1.4 on 2022-12-29 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prediccion', '0002_alter_prediccion_arritmia_alter_prediccion_fevi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prediccion',
            name='estado_vital',
            field=models.IntegerField(blank=True, choices=[(0, 'Fallecido'), (1, 'Vivo')], null=True),
        ),
        migrations.AlterField(
            model_name='prediccion',
            name='prediccion',
            field=models.IntegerField(blank=True, choices=[(0, 'Fallecido'), (1, 'Vivo')], null=True),
        ),
    ]
